### ISSUE TITLE
There are a few console logs left in the code 

### ISSUE THREAD

**Issue by zurda** [fac-15/I-Choose-Who-#9]
We noticed a few console message appears when you view the page both in the frontend and the backend (terminal) : 

1. 

<img width="583" alt="screenshot 2018-11-23 at 10 42 22" src="https://user-images.githubusercontent.com/16784959/48939546-7e280c80-ef0c-11e8-99fc-d8fb134e4cb6.png">

2. 

<img width="527" alt="screenshot 2018-11-23 at 10 40 41" src="https://user-images.githubusercontent.com/16784959/48939530-723c4a80-ef0c-11e8-820b-9ac29690447a.png">

**Comment by jcharnley** [comment]
all the logs are now removed on server and client side
